apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-client-cli
  labels:
    app: admin-client-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-client-cli
  template:
    metadata:
      labels:
        app: admin-client-cli
    spec:
      containers:
        - name: admin
          image: quay.io/strimzi-test-clients/test-clients:latest-kafka-3.9.0
          command: [ "sleep" ]
          args: [ "infinity" ]