apiVersion: batch/v1
kind: Job 
metadata:
    labels:
      app: delete-admin-client-offset-scram
      user-test-app: kafka-clients
    name: delete-admin-client-offset-scram
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: delete-admin-client-offset-scram
        job-name: delete-admin-client-offset-scram
        user-test-app: kafka-clients
      name: delete-admin-client-offset-scram
      namespace: namespace-0
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: TOPIC
          value: "test-topic"
        - name: TOPIC_OPERATION
          value: remove
        - name: TOPICS_COUNT
          value: "100"
        - name: TOPIC_OFFSET
          value: "200"
        - name: LOG_LEVEL
          value: DEBUG
        - name: ADDITIONAL_CONFIG
          value: |
            sasl.mechanism=SCRAM-SHA-512
            security.protocol=SASL_PLAINTEXT
            sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="test-user" password="myPassword";
        image: quay.io/strimzi-test-clients/test-client-kafka-admin:latest-kafka-3.1.0
        imagePullPolicy: IfNotPresent
        name: delete-admin-client-offset-scram
      restartPolicy: "Never"
      
      
