apiVersion: batch/v1
kind: Job 
metadata:
    labels:
      app: delete-admin-client-1
      user-test-app: kafka-clients
    name: delete-admin-client-1
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: delete-admin-client-1
        job-name: delete-admin-client-1
        user-test-app: kafka-clients
      name: delete-admin-client-1
      namespace: namespace-0
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: TOPIC
          value: "test-topic"
        - name: TOPIC_OPERATION
          value: remove
        - name: TOPICS_COUNT
          value: "100"
        - name: LOG_LEVEL
          value: DEBUG
        image: quay.io/strimzi-test-clients/test-client-kafka-admin:latest-kafka-3.3.1
        imagePullPolicy: IfNotPresent
        name: delete-admin-client-1
      restartPolicy: "Never"