apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: http-consumer
    user-test-app: kafka-clients
  name: http-consumer
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: http-consumer
        job-name: http-consumer
        user-test-app: kafka-clients
      name: http-consumer
      namespace: my-project
    spec:
      containers:
        - env:
            - name: HOSTNAME
              value: my-cluster-bridge-service
            - name: PORT
              value: "8080"
            - name: POLL_INTERVAL
              value: "1000"
            - name: GROUP_ID
              value: my-group
            - name: TOPIC
              value: my-topic
            - name: MESSAGE_COUNT
              value: "100"
            - name: LOG_LEVEL
              value: DEBUG
            - name: CLIENT_TYPE
              value: HttpConsumer
          image: quay.io/strimzi-test-clients/test-clients:0.5.2-kafka-3.4.0
          imagePullPolicy: IfNotPresent
          name: http-consumer
      restartPolicy: "Never"